#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Epitech.Intra.Droid.Resource", IsApplication=true)]

namespace Epitech.Intra.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::OxyPlot.Xamarin.Forms.Platform.Android.Resource.String.library_name = global::Epitech.Intra.Droid.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int git_logo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int logo_blue = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menu24 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menuiconscalendar = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menuiconscrowd = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menuiconsdisconnect = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menuiconselearning = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menuiconsinfo = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int menuiconsleaderboard = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int menuiconsnotifications = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int menuiconsprofile = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int menuiconsprojects = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int library_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
